services:
    courses-database:
      image: 'mariadb:10.8.3'
      command: '--default-authentication-plugin=mysql_native_password'
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: courses
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - '5002:3306'
      networks:
        - courses-network
    courses-backend:
        container_name: courses-backend
        build:
            context: courses-backend
            dockerfile: Dockerfile
        ports:
            - 5001:5001
        networks:
            - courses-network
        depends_on:
            - courses-database
    courses-frontend:
        container_name: courses-frontend
        build:
            context: courses-frontend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
networks:
  courses-network:
